// Package measurementhttp defines the HTTP transport discriminators shared by
// netspeedd measurement endpoints. It deliberately depends only on the standard
// library so the stream contract can be tested independently of the daemon.
package measurementhttp

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

const (
	// TransportVersion identifies the optional HTTP transport-discriminator
	// extension. It does not replace the strict measurement protocol version.
	TransportVersion = 1

	// CacheControl is applied to every measurement response so intermediaries do
	// not cache, compress, or otherwise transform measured payloads.
	CacheControl = "no-store, no-transform"

	DefaultChunkBytes = 1 << 20 // 1 MiB
	MinChunkBytes     = 4 << 10 // 4 KiB
	MaxChunkBytes     = 1 << 20 // 1 MiB
)

// Payload identifies the byte pattern generated by /__down.
type Payload string

const (
	PayloadRandom Payload = "random"
	PayloadZero   Payload = "zero"
)

// Framing identifies whether /__down supplies a known length or deliberately
// streams without Content-Length. HTTP/2 and HTTP/3 use DATA frames rather than
// HTTP/1.1 chunked transfer coding, but retain the same streamed semantics.
type Framing string

const (
	FramingFixed   Framing = "fixed"
	FramingChunked Framing = "chunked"
)

// DownloadOptions is the normalized /__down request contract.
type DownloadOptions struct {
	Bytes      int64
	Payload    Payload
	Framing    Framing
	ChunkBytes int
	Flush      bool
}

// ParameterError reports a client-controlled measurement parameter error and
// the HTTP status appropriate for that endpoint.
type ParameterError struct {
	StatusCode int
	Message    string
}

func (err *ParameterError) Error() string { return err.Message }

// StatusCode returns the status carried by a ParameterError or fallback.
func StatusCode(err error, fallback int) int {
	var parameterError *ParameterError
	if errors.As(err, &parameterError) && parameterError.StatusCode != 0 {
		return parameterError.StatusCode
	}
	return fallback
}

// ParseDownload normalizes /__down query discriminators. Unknown query
// parameters remain accepted for Cloudflare-style correlation labels.
func ParseDownload(request *http.Request, maxBytes int64) (DownloadOptions, error) {
	options := DownloadOptions{
		Payload:    PayloadRandom,
		Framing:    FramingFixed,
		ChunkBytes: DefaultChunkBytes,
	}
	query := request.URL.Query()

	if raw := strings.TrimSpace(query.Get("bytes")); raw != "" {
		value, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return options, badRequest("invalid bytes parameter")
		}
		if value < 0 {
			return options, badRequest("bytes cannot be negative")
		}
		if value > maxBytes {
			return options, badRequest("bytes exceeds maximum allowed")
		}
		options.Bytes = value
	}

	rawPayload, err := aliasedDiscriminator(query, "payload", "pattern", "fill")
	if err != nil {
		return options, err
	}
	switch normalizeToken(rawPayload) {
	case "", "random", "prng", "pseudorandom":
		options.Payload = PayloadRandom
	case "zero", "zeros", "zerofill":
		options.Payload = PayloadZero
	default:
		return options, badRequest("payload must be random or zero")
	}

	rawFraming, err := aliasedDiscriminator(query, "framing", "stream")
	if err != nil {
		return options, err
	}
	switch normalizeToken(rawFraming) {
	case "", "fixed", "length", "contentlength":
		options.Framing = FramingFixed
	case "chunked", "streamed":
		options.Framing = FramingChunked
	default:
		return options, badRequest("framing must be fixed or chunked")
	}

	if raw := strings.TrimSpace(query.Get("chunkBytes")); raw != "" {
		value, err := strconv.ParseInt(raw, 10, 32)
		if err != nil || value < MinChunkBytes || value > MaxChunkBytes {
			return options, badRequest(fmt.Sprintf("chunkBytes must be between %d and %d", MinChunkBytes, MaxChunkBytes))
		}
		options.ChunkBytes = int(value)
	}

	flushSpecified := false
	if raw := strings.TrimSpace(query.Get("flush")); raw != "" {
		value, err := strconv.ParseBool(raw)
		if err != nil {
			return options, badRequest("flush must be a boolean")
		}
		options.Flush = value
		flushSpecified = true
	}
	if options.Framing == FramingChunked && !flushSpecified {
		options.Flush = true
	}
	return options, nil
}

// ParseUploadExpectedBytes parses Cloudflare-style /__up?bytes=N correlation.
// The query is optional; when supplied, the daemon verifies it against both a
// known Content-Length and the actual number of bytes consumed.
func ParseUploadExpectedBytes(request *http.Request, maxBytes int64) (int64, bool, error) {
	raw := strings.TrimSpace(request.URL.Query().Get("bytes"))
	if raw == "" {
		return 0, false, nil
	}
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return 0, false, badRequest("invalid bytes parameter")
	}
	if value < 0 {
		return 0, false, badRequest("bytes cannot be negative")
	}
	if value > maxBytes {
		return 0, false, &ParameterError{StatusCode: http.StatusRequestEntityTooLarge, Message: "bytes exceeds maximum allowed"}
	}
	return value, true, nil
}

// ValidateIdentityContentEncoding rejects compressed upload bodies. Measuring a
// decoded gzip or Brotli body would report decompression and proxy behavior
// rather than the bytes placed on the wire by the client.
func ValidateIdentityContentEncoding(request *http.Request) error {
	values := request.Header.Values("Content-Encoding")
	for _, line := range values {
		for _, raw := range strings.Split(line, ",") {
			encoding := strings.TrimSpace(raw)
			if encoding == "" {
				return &ParameterError{StatusCode: http.StatusUnsupportedMediaType, Message: "invalid Content-Encoding"}
			}
			if !strings.EqualFold(encoding, "identity") {
				return &ParameterError{StatusCode: http.StatusUnsupportedMediaType, Message: "compressed measurement uploads are not supported"}
			}
		}
	}
	return nil
}

// SetResponseHeaders applies the common anti-cache, anti-transform, and
// reverse-proxy buffering controls to a measurement response.
func SetResponseHeaders(header http.Header, measurement string) {
	header.Set("Cache-Control", CacheControl)
	header.Set("CDN-Cache-Control", "no-store")
	header.Set("Surrogate-Control", "no-store")
	header.Set("Pragma", "no-cache")
	header.Set("Expires", "0")
	header.Set("X-Accel-Buffering", "no")
	header.Set("X-Content-Type-Options", "nosniff")
	if measurement != "" {
		header.Set("X-Netspeed-Measurement", measurement)
	}
}

// SetDownloadHeaders records the selected discriminators and applies or omits
// Content-Length according to the selected framing.
func SetDownloadHeaders(header http.Header, options DownloadOptions) {
	header.Set("Content-Type", "application/octet-stream")
	header.Set("X-Netspeed-Payload", string(options.Payload))
	header.Set("X-Netspeed-Framing", string(options.Framing))
	header.Set("X-Netspeed-Chunk-Bytes", strconv.Itoa(options.ChunkBytes))
	if options.Framing == FramingFixed {
		header.Set("Content-Length", strconv.FormatInt(options.Bytes, 10))
	} else {
		header.Del("Content-Length")
	}
}

var (
	streamBufferPool = sync.Pool{New: func() any {
		return make([]byte, MaxChunkBytes)
	}}
	payloadSeedCounter atomic.Uint64
)

// Validate verifies a normalized download transport contract before bytes are
// committed. ParseDownload already produces valid options; this guard also
// protects internal callers from accidentally streaming stale pooled data.
func (options DownloadOptions) Validate() error {
	if options.Bytes < 0 {
		return fmt.Errorf("invalid byte count %d", options.Bytes)
	}
	switch options.Payload {
	case PayloadRandom, PayloadZero:
	default:
		return fmt.Errorf("invalid payload %q", options.Payload)
	}
	switch options.Framing {
	case FramingFixed, FramingChunked:
	default:
		return fmt.Errorf("invalid framing %q", options.Framing)
	}
	if options.ChunkBytes < MinChunkBytes || options.ChunkBytes > MaxChunkBytes {
		return fmt.Errorf("invalid chunk size %d", options.ChunkBytes)
	}
	return nil
}

// Flush commits headers and any pending stream data when the underlying HTTP
// implementation supports it. A successful no-op on an unsupported test writer
// keeps the transport helper usable behind wrappers and in unit tests.
func Flush(writer http.ResponseWriter) error {
	err := http.NewResponseController(writer).Flush()
	if errors.Is(err, http.ErrNotSupported) {
		return nil
	}
	return err
}

// Stream writes exactly options.Bytes bytes. Random mode uses a per-request
// SplitMix64 stream so adjacent chunks do not repeat; zero mode avoids generator
// CPU for very high-rate tests. The pseudorandom stream is compression-resistant
// measurement data, not cryptographic randomness.
func Stream(writer http.ResponseWriter, options DownloadOptions) (int64, error) {
	if err := options.Validate(); err != nil {
		return 0, err
	}
	if options.Bytes == 0 {
		return 0, nil
	}

	buffer := streamBufferPool.Get().([]byte)
	defer streamBufferPool.Put(buffer)
	buffer = buffer[:options.ChunkBytes]

	var generator splitMix64
	if options.Payload == PayloadZero {
		clear(buffer)
	} else {
		seed := payloadSeedCounter.Add(0x9e3779b97f4a7c15) ^ uint64(time.Now().UnixNano())
		if seed == 0 {
			seed = 0x6a09e667f3bcc909
		}
		generator.state = seed
	}

	var written int64
	for written < options.Bytes {
		remaining := options.Bytes - written
		chunkLength := len(buffer)
		if remaining < int64(chunkLength) {
			chunkLength = int(remaining)
		}
		chunk := buffer[:chunkLength]
		if options.Payload == PayloadRandom {
			generator.fill(chunk)
		}
		n, err := writeFull(writer, chunk)
		written += int64(n)
		if err != nil {
			return written, err
		}
		if options.Flush {
			if err := Flush(writer); err != nil {
				return written, err
			}
		}
	}
	return written, nil
}

func badRequest(message string) error {
	return &ParameterError{StatusCode: http.StatusBadRequest, Message: message}
}

func normalizeToken(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	value = strings.NewReplacer("-", "", "_", "", " ", "").Replace(value)
	return value
}

func aliasedDiscriminator(query url.Values, names ...string) (string, error) {
	var selected string
	var selectedNormalized string
	for _, name := range names {
		for _, raw := range query[name] {
			trimmed := strings.TrimSpace(raw)
			if trimmed == "" {
				continue
			}
			normalized := normalizeToken(trimmed)
			if selected != "" && normalized != selectedNormalized {
				return "", badRequest(fmt.Sprintf("conflicting %s discriminator values", names[0]))
			}
			selected = trimmed
			selectedNormalized = normalized
		}
	}
	return selected, nil
}

func writeFull(writer io.Writer, payload []byte) (int, error) {
	written := 0
	for written < len(payload) {
		n, err := writer.Write(payload[written:])
		written += n
		if err != nil {
			return written, err
		}
		if n == 0 {
			return written, io.ErrShortWrite
		}
	}
	return written, nil
}

type splitMix64 struct {
	state uint64
}

func (generator *splitMix64) next() uint64 {
	generator.state += 0x9e3779b97f4a7c15
	value := generator.state
	value = (value ^ (value >> 30)) * 0xbf58476d1ce4e5b9
	value = (value ^ (value >> 27)) * 0x94d049bb133111eb
	return value ^ (value >> 31)
}

func (generator *splitMix64) fill(buffer []byte) {
	for len(buffer) >= 8 {
		binary.LittleEndian.PutUint64(buffer[:8], generator.next())
		buffer = buffer[8:]
	}
	if len(buffer) == 0 {
		return
	}
	value := generator.next()
	for index := range buffer {
		buffer[index] = byte(value)
		value >>= 8
	}
}
